---
abstract: 'Subclassable and hostless URIs'
author:
  - 'Rafael Kitover <rkitover@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-SmartURI
no_index:
  directory:
    - inc
    - t
requires:
  Class::C3::Componentised: 0
  File::Find::Rule: 0
  List::MoreUtils: 0
  List::Util: 0
  MRO::Compat: 0.09
  Moose: 0
  Scalar::Util: 0
  URI: 0
  namespace::clean: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.028
